---
name: Add a new OSS GitHub org to the Moderne public tenant 

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'The GH org'
        required: true
env:
  GITHUB_TOKEN: ${{secrets.PAT}}
jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
          repository: moderneinc/jenkins-ingest
      - name: Adds an org
        run: ./add-github-organization.sh ${{ inputs.org }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: add/${{ inputs.org }}
          token: ${{secrets.PAT}}
          title: "[Auto] The ${{ inputs.org }} GitHub organization is added"
          commit-message: "[Auto] The ${{ inputs.org }} GitHub organization is added"
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"      
