---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: { }
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_SWITCHES: --console=plain --info --warning-mode=all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: build
        timeout-minutes: 20
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.GRADLE_SWITCHES }} build
          build-root-directory: parser
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: parser/build/reports/
      - name: Validate repos.csv
        run: ./validate-repos.csv.sh
